spring:
  profiles:
    include: jwt, cloud, alarm
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      encoding: UTF-8
    mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB
logging:
  config: classpath:logback/logback-default.xml

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/dodeuni;MODE=MYSQL;AUTO_SERVER=true
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}:3306/dodeuni?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none